## Задание #1
Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Используя математические операции, посчитать коэффициенты линейной регрессии,
приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная).
Произвести расчет как с использованием intercept, так и без.

In [615]:
import numpy as np

n = 10
x = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

Проведем рассчет с использованием интерцепта:

In [616]:
B1_1 = (np.mean(x * y) - (np.mean(x) * np.mean(y))) / (np.mean(x**2) - np.mean(x) ** 2)
B1_1

2.620538882402765

In [617]:
A1 = np.mean(y) - B1_1 * np.mean(x)
A1

444.1773573243596

тоже самое с использованием матричного метода:

In [618]:
x1 = x.reshape(len(x), 1)
y1 = y.reshape(len(y), 1)
X1 = np.hstack([np.ones((10,1)), x1])

In [619]:
B1_1_1 = np.dot(np.linalg.inv(np.dot(X1.T,X1)),X1.T@y1)
B1_1_1

array([[444.17735732],
       [  2.62053888]])

In [620]:
B1_1_2 = np.linalg.pinv(X1).dot(y1)
B1_1_2

array([[444.17735732],
       [  2.62053888]])

In [621]:
y_hat1 = A1 + (B1_1 * x)
y_hat1

array([535.89621821, 562.10160703, 942.07974498, 968.2851338 ,
       548.99891262, 627.61507909, 585.68645697, 837.25818968,
       758.64202321, 732.43663439])

In [622]:
mse1 = np.mean((y - y_hat1) ** 2)
mse1

6470.414201176658

Проведем рассчет без использования интерцепта:

In [623]:
B1_2 = np.mean(y/x)
B1_2

8.732607022607024

In [624]:
y_hat2 = B1_2 * x
y_hat2

array([ 305.64124579,  392.96731602, 1659.1953343 , 1746.52140452,
        349.3042809 ,  611.28249158,  471.56077922, 1309.89105339,
       1047.91284271,  960.58677249])

тоже самое с использованием матричного метода:

In [625]:
x2 = x.reshape(len(x), 1)
y2 = y.reshape(len(y), 1)
B1_2_1 = np.dot(np.linalg.inv(np.dot(x2.T,x2)),x2.T@y2)
B1_2_1

array([[5.88982042]])

In [626]:
B1_2_2 = np.linalg.pinv(x2).dot(y2)
B1_2_2

array([[5.88982042]])

In [627]:
mse2 = np.mean((y - y_hat2) ** 2)
mse2

167851.56502857123

In [628]:
import pandas as pd

df = pd.DataFrame({'x': x, 'y': y, 'y_hat1': y_hat1, 'y_hat2': y_hat2}, columns=['x', 'y', 'y_hat1', 'y_hat2'])
df

x    y      y_hat1       y_hat2
0   35  401  535.896218   305.641246
1   45  574  562.101607   392.967316
2  190  874  942.079745  1659.195334
3  200  919  968.285134  1746.521405
4   40  459  548.998913   349.304281
5   70  739  627.615079   611.282492
6   54  653  585.686457   471.560779
7  150  902  837.258190  1309.891053
8  120  746  758.642023  1047.912843
9  110  832  732.436634   960.586772

## Задание #2
Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [629]:
alpha = 1e-6
alpha

1e-06

In [630]:
B1 = 0.1
for i in range(3000):
    B1 -= alpha*(2/n)*np.sum((B1*x-y)*x)
    if i%500 == 0:
        print('Iteration: {i}, B1={B1}, mse={mse}'.format(i=i, B1=B1, mse=np.mean((B1*x-y)**2)))

Iteration: 0, B1=0.25952808, mse=493237.7212546963
Iteration: 500, B1=5.889815595583751, mse=56516.858416040064
Iteration: 1000, B1=5.8898204201285544, mse=56516.85841571941
Iteration: 1500, B1=5.889820420132673, mse=56516.85841571943
Iteration: 2000, B1=5.889820420132673, mse=56516.85841571943
Iteration: 2500, B1=5.889820420132673, mse=56516.85841571943


## Задание #3
В каких случаях для вычисления доверительных интервалов и проверки статистических гипотез используется таблица значений функции Лапласа,
а в каких - таблица критических точек распределения Стьюдента?

- При неизвестной сигме/дисперсии генеральной совокупности используется критерий Стьюдента(таблица критических точек распределения Стьюдента).

- Если сигма/дисперсия генеральной совокупности известна - используется Z критерий (таблица значений функции Лапласа)

## Задание #4
Произвести вычисления как в пункте 2, но с вычислением intercept.
Учесть, что изменение коэффициентов должно производиться на каждом шаге одновременно
(то есть изменение одного коэффициента не должно влиять на изменение другого во время одной итерации).

In [631]:
alpha = 1e-4
alpha

0.0001

In [632]:
x = x.reshape(1, 10)
X = np.vstack([np.ones((1, 10)), x])
y = y.reshape(len(y), 1)
W = [1, 0.1]

for i in range(4000000):
    predict = np.dot(W,X)
    W = W - alpha*(1/n)*np.dot((predict - y), X.T)
    if i%100000 == 0:
        w_history = W.T
        print(i, w_history[0][0], w_history[1][0])


0 1.038986 4.0182340000000005
100000 369.3466815229913 0.23298241872678535
200000 398.49497394059296 0.018438099332876948
300000 400.8017536277315 0.0014591809496521647
400000 400.98431089210663 0.00011547877064858756
500000 400.998758372706 9.13892583896679e-06
600000 400.9999017383009 7.232495494284433e-07
700000 400.99999222362175 5.723758208974189e-08
800000 400.9999993845814 4.529753182696159e-09
900000 400.99999995129116 3.5851873151827197e-10
1000000 400.9999999961029 2.868464180651348e-11
1100000 400.99999999887973 8.24545993950854e-12
1200000 400.99999999887973 8.24545993950854e-12
1300000 400.99999999887973 8.24545993950854e-12
1400000 400.99999999887973 8.24545993950854e-12
1500000 400.99999999887973 8.24545993950854e-12
1600000 400.99999999887973 8.24545993950854e-12
1700000 400.99999999887973 8.24545993950854e-12
1800000 400.99999999887973 8.24545993950854e-12
1900000 400.99999999887973 8.24545993950854e-12
2000000 400.99999999887973 8.24545993950854e-12
2100000 400.999999