## Задание #1
Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Используя математические операции, посчитать коэффициенты линейной регрессии,
приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная).
Произвести расчет как с использованием intercept, так и без.

In [754]:
import numpy as np

n = 10
x = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

Проведем рассчет с использованием интерсепта:

In [755]:
B1_1 = (np.mean(x * y) - (np.mean(x) * np.mean(y))) / (np.mean(x**2) - np.mean(x) ** 2)
B1_1

2.620538882402765

In [756]:
A1 = np.mean(y) - B1_1 * np.mean(x)
A1

444.1773573243596

тоже самое с использованием матричного метода:

In [757]:
x1 = x.reshape(len(x), 1)
y1 = y.reshape(len(y), 1)
X1 = np.hstack([np.ones((10,1)), x1])

In [758]:
B1_1_1 = np.dot(np.linalg.inv(np.dot(X1.T,X1)),X1.T@y1)
B1_1_1

array([[444.17735732],
       [  2.62053888]])

In [759]:
B1_1_2 = np.linalg.pinv(X1).dot(y1)
B1_1_2

array([[444.17735732],
       [  2.62053888]])

In [760]:
y_hat1 = A1 + (B1_1 * x)
y_hat1

array([535.89621821, 562.10160703, 942.07974498, 968.2851338 ,
       548.99891262, 627.61507909, 585.68645697, 837.25818968,
       758.64202321, 732.43663439])

In [761]:
mse1 = np.mean((y - y_hat1) ** 2)
mse1

6470.414201176658

Проведем рассчет без использования интерсепта:

In [762]:
B1_2 = np.mean(y) / np.mean(x)
B1_2

7.000986193293885

In [763]:
y_hat2 = B1_2 * x
y_hat2

array([ 245.03451677,  315.0443787 , 1330.18737673, 1400.19723866,
        280.03944773,  490.06903353,  378.05325444, 1050.14792899,
        840.1183432 ,  770.10848126])

тоже самое с использованием матричного метода:

In [764]:
x2 = x.reshape(len(x), 1)
y2 = y.reshape(len(y), 1)
B1_2_1 = np.dot(np.linalg.inv(np.dot(x2.T,x2)),x2.T@y2)
B1_2_1

array([[5.88982042]])

In [765]:
B1_2_2 = np.linalg.pinv(x2).dot(y2)
B1_2_2

array([[5.88982042]])

In [766]:
mse2 = np.mean((y - y_hat2) ** 2)
mse2

73526.6800654739

In [767]:
import pandas as pd

df = pd.DataFrame({'x': x, 'y': y, 'y_hat1': y_hat1, 'y_hat2': y_hat2}, columns=['x', 'y', 'y_hat1', 'y_hat2'])
df

x    y      y_hat1       y_hat2
0   35  401  535.896218   245.034517
1   45  574  562.101607   315.044379
2  190  874  942.079745  1330.187377
3  200  919  968.285134  1400.197239
4   40  459  548.998913   280.039448
5   70  739  627.615079   490.069034
6   54  653  585.686457   378.053254
7  150  902  837.258190  1050.147929
8  120  746  758.642023   840.118343
9  110  832  732.436634   770.108481

## Задание #2
Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [768]:
alpha = 1e-6
alpha

1e-06

In [769]:
B1 = 0.1
for i in range(3000):
    B1 -= alpha*(2/n)*np.sum((B1*x-y)*x)
    if i%500 == 0:
        print('Iteration: {i}, B1={B1}, mse={mse}'.format(i=i, B1=B1, mse=np.mean((B1*x-y)**2)))

Iteration: 0, B1=0.25952808, mse=493237.7212546963
Iteration: 500, B1=5.889815595583751, mse=56516.858416040064
Iteration: 1000, B1=5.8898204201285544, mse=56516.85841571941
Iteration: 1500, B1=5.889820420132673, mse=56516.85841571943
Iteration: 2000, B1=5.889820420132673, mse=56516.85841571943
Iteration: 2500, B1=5.889820420132673, mse=56516.85841571943


## Задание #3
В каких случаях для вычисления доверительных интервалов и проверки статистических гипотез используется таблица значений функции Лапласа,
а в каких - таблица критических точек распределения Стьюдента?

- При неизвестной сигме/дисперсии генеральной совокупности используется критерий Стьюдента(таблица критических точек распределения Стьюдента).

- Если сигма/дисперсия генеральной совокупности известна - используется Z критерий (таблица значений функции Лапласа)

## Задание #4
Произвести вычисления как в пункте 2, но с вычислением intercept.
Учесть, что изменение коэффициентов должно производиться на каждом шаге одновременно
(то есть изменение одного коэффициента не должно влиять на изменение другого во время одной итерации).

In [770]:
alpha = 1e-4
alpha

0.0001

In [771]:
x = x.reshape(1, 10)
X = np.vstack([np.ones((1, 10)), x])
y = y.reshape(len(y), 1)
W = [1, 0.1]

for i in range(3000000):
    predict = np.dot(W,X)
    W = W - alpha*(1/n)*np.dot((predict - y), X.T)
    if i%500000 == 0:
        w_history = W.T
        print(i, w_history[0][0], w_history[1][0])


0 1.038986 4.0182340000000005
500000 400.998758372706 9.13892583896679e-06
1000000 400.9999999961029 2.868464180651348e-11
1500000 400.99999999887973 8.24545993950854e-12
2000000 400.99999999887973 8.24545993950854e-12
2500000 400.99999999887973 8.24545993950854e-12
